eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6001/eureka/
  instance:
    prefer-ip-address: true #使用ip注册到eureka服务列表
server:
  port: 7002
spring:
  application:
    name: product-service
datasource:
  username:root
  password:root
  url:jdbc:mysql:///aigou-product?useUnicode=true&characterEncoding=utf8
  driver-class-name:com.mysql.jdbc.Driver